=== opengeospatial/2D-Tile-Matrix-Set/schemas/tms/2.0/xml/tileMatrixSet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Edited with XMLSpy v2008 sp1 (http://www.altova.com) by Joan MasÃ³
	(UAB-CREAF-MiraMon). Based on previous documents of Keith Pomakis. -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tms="http://www.opengis.net/tms/2.0" xmlns:tmsc="http://www.opengis.net/tms/2.0/common" targetNamespace="http://www.opengis.net/tms/2.0" elementFormDefault="qualified" xml:lang="en">
	<annotation>
		<appinfo>TileMatrixSet 2021-02-02</appinfo>
		<documentation>
			This XML Schema Document encodes the TileMatrixSet data structures.
			TMS is an OGC Standard Copyright (c) 2021 Open Geospatial Consortium, Inc. All Rights Reserved.
		    To obtain additional rights of use, visit http://www.opengeospatial.org/legal/.
		</documentation>
	</annotation>
	<!-- *********************************************************************
	             Includes and imports.
          ********************************************************************* -->
	<!--import namespace="http://www.w3.org/1999/xlink" schemaLocation="../../../xlink/1.0.0/xlinks.xsd"/-->
	<import namespace="http://www.opengis.net/tms/2.0/common" schemaLocation="common.xsd"/>
	<!-- ********************************************************************* -->
	<!-- **  The TileMatrixSet element.                                         ** -->
	<!-- ********************************************************************* -->
	<element name="TileMatrixSet">
		<annotation>
			<documentation>Describes a particular set of tile matrices.</documentation>
		</annotation>
		<complexType>
			<complexContent>
				<extension base="tmsc:DescriptionType">
					<sequence>
						<element ref="tmsc:Identifier" minOccurs="0">
							<annotation>
								<documentation>Tile matrix set identifier</documentation>
							</annotation>
						</element>
						<element name="uri" type="anyURI" minOccurs="0">
							<annotation>
								<documentation>Reference to an official source for this tileMatrixSet</documentation>
							</annotation>
						</element>
						<element ref="tmsc:BoundingBox" minOccurs="0">
							<annotation>
								<documentation>
									Minimum bounding rectangle surrounding
									the visible layer presented by this tile matrix
									set, in the supported CRS </documentation>
							</annotation>
						</element>
						<element ref="tmsc:CRS">
							<annotation>
								<documentation>Reference to one coordinate reference
								system (CRS).</documentation>
							</annotation>
						</element>
						<element name="OrderedAxes" type="string" minOccurs="0">
							<annotation>
								<documentation>
									Names of dimensions in this CRS, separated by a comma.
                           These names are specified by the CRS definition,
                           but can also be specified here to avoid any ambiguity.
                        </documentation>
							</annotation>
						</element>
						<element name="WellKnownScaleSet" type="anyURI" minOccurs="0">
							<annotation>
								<documentation>Reference to a well known scale set.
									http://www.opengis.net/def/wkss/OGC/1.0/GlobalCRS84Scale,
									http://www.opengis.net/def/wkss/OGC/1.0/GlobalCRS84Pixel,
									http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad,
									http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible and
									http://www.opengis.net/def/wkss/OGC/1.0/WorldMercatorWGS84 are
								possible values that are defined in Annex C. It has to be consistent with the
								crs and with the ScaleDenominators of the TileMatrix elements.
								</documentation>
							</annotation>
						</element>
						<element ref="tms:TileMatrix" maxOccurs="unbounded">
							<annotation>
								<documentation>Describes a scale level and its tile matrix.</documentation>
							</annotation>
						</element>
						<any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded">
							<annotation>
								<documentation>This is an extension point for other properties in the TileMatrixSet.</documentation>
							</annotation>
						</any>
					</sequence>
					<attribute name="id" type="string">
						<annotation>
							<documentation/>
						</annotation>
					</attribute>
				</extension>
			</complexContent>
		</complexType>
	</element>
	<!-- ********************************************************************* -->
	<!-- **  The TileMatrix element.                                                ** -->
	<!-- ********************************************************************* -->
	<element name="TileMatrix">
		<annotation>
			<documentation>Describes a particular tile matrix.</documentation>
		</annotation>
		<complexType>
			<complexContent>
				<extension base="tmsc:DescriptionType">
					<sequence>
						<element ref="tmsc:Identifier">
							<annotation>
								<documentation>Tile matrix identifier. Typically an abreviation of
								the ScaleDenominator value or its equivalent pixel size</documentation>
							</annotation>
						</element>
						<element name="ScaleDenominator" type="double">
							<annotation>
								<documentation>Scale denominator of this tile matrix</documentation>
							</annotation>
						</element>
						<element name="CellSize" type="double">
							<annotation>
								<documentation>Cell size of this tile matrix</documentation>
							</annotation>
						</element>
						<element name="CornerOfOrigin" minOccurs="0">
							<annotation>
								<documentation>
									The corner of the tile matrix (_topLeft_ or _bottomLeft_) used as the origin for numbering tile rows and columns. This corner is also a corner of the (0, 0) tile.
								</documentation>
							</annotation>
							<simpleType>
								<restriction base="string">
									<enumeration value="topLeft"/>
									<enumeration value="bottomLeft"/>
								</restriction>
							</simpleType>
						</element>
						<element name="PointOfOrigin" type="tmsc:PositionType">
							<annotation>
								<documentation>
									Precise position in CRS coordinates of the corner of origin (e.g. the top-left corner) for this tile matrix.
									This position is also a corner of the (0, 0) tile.
									In previous version, this was 'topLeftCorner' and 'cornerOfOrigin' did not exist.
								</documentation>
							</annotation>
						</element>
						<element name="TileWidth" type="positiveInteger">
							<annotation>
								<documentation>Width of each tile of this tile matrix in pixels.</documentation>
							</annotation>
						</element>
						<element name="TileHeight" type="positiveInteger">
							<annotation>
								<documentation>Height of each tile of this tile matrix in pixels</documentation>
							</annotation>
						</element>
						<element name="MatrixWidth" type="positiveInteger">
							<annotation>
								<documentation>Width of the matrix (number of tiles in width)</documentation>
							</annotation>
						</element>
						<element name="MatrixHeight" type="positiveInteger">
							<annotation>
								<documentation>Height of the matrix (number of tiles in height)</documentation>
							</annotation>
						</element>
						<element name="VariableMatrixWidth" minOccurs="0" maxOccurs="unbounded">
							<annotation>
								<documentation>The rows mention in this array apply the coalece mechanims to fuse n contiguous tiles in the width axis into a single tile</documentation>
							</annotation>
							<complexType>
								<sequence>
									<element name="Coalesce" type="positiveInteger">
										<annotation>
											<documentation>Number of tiles in width that coalesce in a single tile for these rows</documentation>
										</annotation>
									</element>
									<element name="MinTileRow" type="nonNegativeInteger">
										<annotation>
											<documentation>First tile row where the coalescence factor applies for this tilematrix</documentation>
										</annotation>
									</element>
									<element name="MaxTileRow" type="nonNegativeInteger">
										<annotation>
											<documentation>Last tile row where the coalescence factor applies for this tilematrix</documentation>
										</annotation>
									</element>
								</sequence>
							</complexType>
						</element>
						<any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded">
							<annotation>
								<documentation>This is an extension point for other properties in the TileMatrix.</documentation>
							</annotation>
						</any>
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>
</schema>

=== opengeospatial/2D-Tile-Matrix-Set/registry/xml/GNOSISGlobalGrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<TileMatrixSet id="GNOSISGlobalGrid" xmlns="http://www.opengis.net/tms/2.0" xmlns:tmsc="http://www.opengis.net/tms/2.0/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/tms/2.0 ../../tilematrixset.xsd">
   <tmsc:Title>GNOSIS Global Grid</tmsc:Title>
   <tmsc:Identifier>GNOSISGlobalGrid</tmsc:Identifier>
   <uri>http://www.opengis.net/def/tilematrixset/OGC/1.0/GNOSISGlobalGrid</uri>
   <tmsc:CRS>
      <tmsc:URI>http://www.opengis.net/def/crs/EPSG/0/4326</tmsc:URI>
   </tmsc:CRS>
   <OrderedAxes>Lat,Lon</OrderedAxes>
   <WellKnownScaleSet>http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad</WellKnownScaleSet>
   <TileMatrix>
      <tmsc:Identifier>0</tmsc:Identifier>
      <ScaleDenominator>139770566.0071794</ScaleDenominator>
      <CellSize>0.3515625</CellSize>
      <CornerOfOrigin>topLeft</CornerOfOrigin>
      <PointOfOrigin>90 -180</PointOfOrigin>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>4</MatrixWidth>
      <MatrixHeight>2</MatrixHeight>
   </TileMatrix>
   <TileMatrix>
      <tmsc:Identifier>1</tmsc:Identifier>
      <ScaleDenominator>69885283.00358972</ScaleDenominator>
      <CellSize>0.17578125</CellSize>
      <CornerOfOrigin>topLeft</CornerOfOrigin>
      <PointOfOrigin>90 -180</PointOfOrigin>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>8</MatrixWidth>
      <MatrixHeight>4</MatrixHeight>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>0</MinTileRow><MaxTileRow>0</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>3</MinTileRow><MaxTileRow>3</MaxTileRow></VariableMatrixWidth>
   </TileMatrix>
   <TileMatrix>
      <tmsc:Identifier>2</tmsc:Identifier>
      <ScaleDenominator>34942641.50179486</ScaleDenominator>
      <CellSize>0.087890625</CellSize>
      <CornerOfOrigin>topLeft</CornerOfOrigin>
      <PointOfOrigin>90 -180</PointOfOrigin>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>16</MatrixWidth>
      <MatrixHeight>8</MatrixHeight>
      <VariableMatrixWidth><Coalesce>4</Coalesce><MinTileRow>0</MinTileRow><MaxTileRow>0</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>1</MinTileRow><MaxTileRow>1</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>6</MinTileRow><MaxTileRow>6</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>4</Coalesce><MinTileRow>7</MinTileRow><MaxTileRow>7</MaxTileRow></VariableMatrixWidth>
   </TileMatrix>
   <TileMatrix>
      <tmsc:Identifier>3</tmsc:Identifier>
      <ScaleDenominator>17471320.7508974298835</ScaleDenominator>
      <CellSize>0.0439453125</CellSize>
      <CornerOfOrigin>topLeft</CornerOfOrigin>
      <PointOfOrigin>90 -180</PointOfOrigin>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>32</MatrixWidth>
      <MatrixHeight>16</MatrixHeight>
      <VariableMatrixWidth><Coalesce>8</Coalesce><MinTileRow>0</MinTileRow><MaxTileRow>0</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>4</Coalesce><MinTileRow>1</MinTileRow><MaxTileRow>1</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>2</MinTileRow><MaxTileRow>3</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>12</MinTileRow><MaxTileRow>13</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>4</Coalesce><MinTileRow>14</MinTileRow><MaxTileRow>14</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>8</Coalesce><MinTileRow>15</MinTileRow><MaxTileRow>15</MaxTileRow></VariableMatrixWidth>
   </TileMatrix>
   <TileMatrix>
      <tmsc:Identifier>4</tmsc:Identifier>
      <ScaleDenominator>8735660.3754487149417</ScaleDenominator>
      <CellSize>0.02197265625</CellSize>
      <CornerOfOrigin>topLeft</CornerOfOrigin>
      <PointOfOrigin>90 -180</PointOfOrigin>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>64</MatrixWidth>
      <MatrixHeight>32</MatrixHeight>
      <VariableMatrixWidth><Coalesce>16</Coalesce><MinTileRow>0</MinTileRow><MaxTileRow>0</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>8</Coalesce><MinTileRow>1</MinTileRow><MaxTileRow>1</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>4</Coalesce><MinTileRow>2</MinTileRow><MaxTileRow>3</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>4</MinTileRow><MaxTileRow>7</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>2</Coalesce><MinTileRow>24</MinTileRow><MaxTileRow>27</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>4</Coalesce><MinTileRow>28</MinTileRow><MaxTileRow>29</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>8</Coalesce><MinTileRow>30</MinTileRow><MaxTileRow>30</MaxTileRow></VariableMatrixWidth>
      <VariableMatrixWidth><Coalesce>16</Coalesce><MinTileRow>31</MinTileRow><MaxTileRow>31</MaxTileRow></VariableMatrixWidth>
   </TileMatrix>
</TileMatrixSet>

=== opengeospatial/2D-Tile-Matrix-Set/registry/xml/SwissLV95CellSizes.xml
<?xml version="1.0" encoding="UTF-8"?>
<TileMatrixSet id="SwissLV95CellSizes" xmlns="http://www.opengis.net/tms/2.0" xmlns:tmsc="http://www.opengis.net/tms/2.0/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/tms/2.0 https://schemas.opengis.net/tms/2.0/xml/tilematrixset.xsd">
   <tmsc:Title>Switzerland 2D tile matrix set definition</tmsc:Title>
   <tmsc:Identifier>SwissLV95CellSizes</tmsc:Identifier>
   <uri>http://www.opengis.net/def/tilematrixset/OGC/1.0/SwissLV95CellSizes</uri>
   <tmsc:CRS>
      <tmsc:URI>http://www.opengis.net/def/crs/EPSG/0/2056</tmsc:URI>
   </tmsc:CRS>
   <OrderedAxes>E,N</OrderedAxes>
   <TileMatrix>
      <tmsc:Identifier>0</tmsc:Identifier>
      <ScaleDenominator>14285714.285714284</ScaleDenominator>
      <CellSize>4000</CellSize>
      <CornerOfOrigin>topLeft</CornerOfOrigin>
      <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>1</MatrixWidth>
      <MatrixHeight>1</MatrixHeight>
   </TileMatrix>
   <TileMatrix>
    <tmsc:Identifier>1</tmsc:Identifier>
    <ScaleDenominator>7142857.142857142</ScaleDenominator>
    <CellSize>2000</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>1</MatrixWidth>
    <MatrixHeight>1</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>2</tmsc:Identifier>
    <ScaleDenominator>3571428.571428571</ScaleDenominator>
    <CellSize>1000</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>2</MatrixWidth>
    <MatrixHeight>2</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>3</tmsc:Identifier>
    <ScaleDenominator>1785714.2857142854</ScaleDenominator>
    <CellSize>500</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>4</MatrixWidth>
    <MatrixHeight>3</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>4</tmsc:Identifier>
    <ScaleDenominator>892857.1428571427</ScaleDenominator>
    <CellSize>250</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>8</MatrixWidth>
    <MatrixHeight>5</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>5</tmsc:Identifier>
    <ScaleDenominator>357142.8571428571</ScaleDenominator>
    <CellSize>100</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>19</MatrixWidth>
    <MatrixHeight>3</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>6</tmsc:Identifier>
    <ScaleDenominator>178571.42857142855</ScaleDenominator>
    <CellSize>50</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>38</MatrixWidth>
    <MatrixHeight>25</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>7</tmsc:Identifier>
    <ScaleDenominator>71428.57142857142</ScaleDenominator>
    <CellSize>20</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>94</MatrixWidth>
    <MatrixHeight>63</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>8</tmsc:Identifier>
    <ScaleDenominator>35714.28571428571</ScaleDenominator>
    <CellSize>10</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>188</MatrixWidth>
    <MatrixHeight>125</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>9</tmsc:Identifier>
    <ScaleDenominator>17857.142857142855</ScaleDenominator>
    <CellSize>5</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>375</MatrixWidth>
    <MatrixHeight>250</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>10</tmsc:Identifier>
    <ScaleDenominator>8928.571428571428</ScaleDenominator>
    <CellSize>2.5</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>750</MatrixWidth>
    <MatrixHeight>500</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>11</tmsc:Identifier>
    <ScaleDenominator>3571.428571428571</ScaleDenominator>
    <CellSize>1</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>1875</MatrixWidth>
    <MatrixHeight>1250</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>12</tmsc:Identifier>
    <ScaleDenominator>1785.7142857142856</ScaleDenominator>
    <CellSize>0.5</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>3750</MatrixWidth>
    <MatrixHeight>2500</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>13</tmsc:Identifier>
    <ScaleDenominator>892.8571428571428</ScaleDenominator>
    <CellSize>0.25</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>7500</MatrixWidth>
    <MatrixHeight>5000</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>14</tmsc:Identifier>
    <ScaleDenominator>357.1428571428571</ScaleDenominator>
    <CellSize>0.1</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>18750</MatrixWidth>
    <MatrixHeight>12500</MatrixHeight>
 </TileMatrix>
 <TileMatrix>
    <tmsc:Identifier>15</tmsc:Identifier>
    <ScaleDenominator>178.57142857142856</ScaleDenominator>
    <CellSize>0.05</CellSize>
    <CornerOfOrigin>topLeft</CornerOfOrigin>
    <PointOfOrigin>2419995.75 1350004.29</PointOfOrigin>
    <TileWidth>256</TileWidth>
    <TileHeight>256</TileHeight>
    <MatrixWidth>37500</MatrixWidth>
    <MatrixHeight>25000</MatrixHeight>
 </TileMatrix>
</TileMatrixSet>

=== opengeospatial/2D-Tile-Matrix-Set/schemas/tms/2.0/xml/examples/tilematrixset/WorldCRS84Quad.xml
<?xml version="1.0" encoding="UTF-8"?>
<TileMatrixSet id="WorldCRS84Quad" xmlns="http://www.opengis.net/tms/2.0" xmlns:tmsc="http://www.opengis.net/tms/2.0/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/tms/2.0 ../../tilematrixset.xsd">
	<tmsc:Title>CRS84 for the World</tmsc:Title>
	<tmsc:Identifier>WorldCRS84Quad</tmsc:Identifier>
	<tmsc:BoundingBox crs="http://www.opengis.net/def/crs/OGC/1.3/CRS84">
		<tmsc:LowerCorner>-180 -90</tmsc:LowerCorner>
		<tmsc:UpperCorner>180 90</tmsc:UpperCorner>
	</tmsc:BoundingBox>
	<tmsc:SupportedCRS>
		<tmsc:URI>http://www.opengis.net/def/crs/OGC/1.3/CRS84</tmsc:URI>
	</tmsc:SupportedCRS>
	<WellKnownScaleSet>
            http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad
         </WellKnownScaleSet>
	<TileMatrix>
		<tmsc:Identifier>0</tmsc:Identifier>
		<ScaleDenominator>279541132.014358</ScaleDenominator>
		<CellSize>0.703125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>2</MatrixWidth>
		<MatrixHeight>1</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>1</tmsc:Identifier>
		<ScaleDenominator>139770566.007179</ScaleDenominator>
		<CellSize>0.3515625</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>4</MatrixWidth>
		<MatrixHeight>2</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>2</tmsc:Identifier>
		<ScaleDenominator>69885283.0035897</ScaleDenominator>
		<CellSize>0.17578125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>8</MatrixWidth>
		<MatrixHeight>4</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>3</tmsc:Identifier>
		<ScaleDenominator>34942641.5017948</ScaleDenominator>
		<CellSize>0.087890625</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>16</MatrixWidth>
		<MatrixHeight>8</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>4</tmsc:Identifier>
		<ScaleDenominator>17471320.7508974</ScaleDenominator>
		<CellSize>0.0439453125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>32</MatrixWidth>
		<MatrixHeight>16</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>5</tmsc:Identifier>
		<ScaleDenominator>8735660.37544871</ScaleDenominator>
		<CellSize>0.02197265625</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>64</MatrixWidth>
		<MatrixHeight>32</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>6</tmsc:Identifier>
		<ScaleDenominator>4367830.18772435</ScaleDenominator>
		<CellSize>0.010986328125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>128</MatrixWidth>
		<MatrixHeight>64</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>7</tmsc:Identifier>
		<ScaleDenominator>2183915.09386217</ScaleDenominator>
		<CellSize>0.0054931640625</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>256</MatrixWidth>
		<MatrixHeight>128</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>8</tmsc:Identifier>
		<ScaleDenominator>1091957.54693108</ScaleDenominator>
		<CellSize>0.00274658203125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>512</MatrixWidth>
		<MatrixHeight>256</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>9</tmsc:Identifier>
		<ScaleDenominator>545978.773465544</ScaleDenominator>
		<CellSize>0.001373291015625</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>1024</MatrixWidth>
		<MatrixHeight>512</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>10</tmsc:Identifier>
		<ScaleDenominator>272989.386732772</ScaleDenominator>
		<CellSize>0.0006866455078125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>2048</MatrixWidth>
		<MatrixHeight>1024</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>11</tmsc:Identifier>
		<ScaleDenominator>136494.693366386</ScaleDenominator>
		<CellSize>0.00034332275390625</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>4096</MatrixWidth>
		<MatrixHeight>2048</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>12</tmsc:Identifier>
		<ScaleDenominator>68247.346683193</ScaleDenominator>
		<CellSize>0.000171661376953125</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>8192</MatrixWidth>
		<MatrixHeight>4096</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>13</tmsc:Identifier>
		<ScaleDenominator>34123.6733415964</ScaleDenominator>
		<CellSize>8.58306884765625E-05</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>16384</MatrixWidth>
		<MatrixHeight>8192</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>14</tmsc:Identifier>
		<ScaleDenominator>17061.8366707982</ScaleDenominator>
		<CellSize>4.29153442382812E-05</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>32768</MatrixWidth>
		<MatrixHeight>16384</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>15</tmsc:Identifier>
		<ScaleDenominator>8530.91833539913</ScaleDenominator>
		<CellSize>2.14576721191406E-05</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>65536</MatrixWidth>
		<MatrixHeight>32768</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>16</tmsc:Identifier>
		<ScaleDenominator>4265.45916769956</ScaleDenominator>
		<CellSize>1.07288360595703E-05</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>131072</MatrixWidth>
		<MatrixHeight>65536</MatrixHeight>
	</TileMatrix>
	<TileMatrix>
		<tmsc:Identifier>17</tmsc:Identifier>
		<ScaleDenominator>2132.72958384978</ScaleDenominator>
		<CellSize>5.36441802978516E-06</CellSize>
		<PointOfOrigin>-180 90</PointOfOrigin>
		<TileWidth>256</TileWidth>
		<TileHeight>256</TileHeight>
		<MatrixWidth>262144</MatrixWidth>
		<MatrixHeight>131072</MatrixHeight>
	</TileMatrix>
</TileMatrixSet>
